import type { Token } from '@/@types/token'

export const DELEGUA_TOKENS: { [token in Token]: string[] } = {
  keywords: [
    'cada',
    'caso',
    'classe',
    'const',
    'constante',
    'continua',
    'de',
    'em',
    'enquanto',
    'escolha',
    'falhar',
    'fazer',
    'finalmente',
    'fixo',
    'funcao',
    'função',
    'herda',
    'importar',
    'inteiro[]',
    'isto',
    'leia',
    'nulo',
    'padrão',
    'padrao',
    'para',
    'para',
    'pegue',
    'qualquer',
    'qualquer[]',
    'real[]',
    'retorna',
    'se',
    'senão se',
    'senão',
    'senao se',
    'senao',
    'sustar',
    'tente',
    'texto[]',
    'tipo',
    'variavel',
    'variável',
    'vetor',

    /* funções nativas texto*/
    'dividir',
    'fatiar',
    'inclui',
    'maiusculo',
    'minusculo',
    'texto',
    'substituir',
    'subtexto',

    /* funções nativas vetor*/
    'adicionar',
    'concatenar',
    'empilhar',
    'fatiar',
    'inclui',
    'inverter',
    'juntar',
    'mapear',
    'ordenar',
    'remover',
    'removerPrimeiro',
    'removerUltimo',
    'somar',

    /* funções nativas gerais*/
    'aleatorio',
    'aleatorioEntre',
    'algum',
    'encontrarIndice',
    'encontrarUltimoIndice',
    'encontrarUltimo',
    'encontrar',
    'escreva',
    'filtrarPor',
    'incluido',
    'inteiro',
    'paraCada',
    'primeiroEmCondicao',
    'real',
    'reduzir',
    'tamanho',
    'todos',
    'todosEmCondicao',
  ],

  operators: [
    'e',
    'ou',
    '<=',
    '>=',
    '==',
    '!=',
    '=>',
    '+',
    '-',
    '**',
    '*',
    '/',
    '%',
    '++',
    '--',
    '<<',
    '>>',
    '^',
    '!',
    '~',
    '=',
    '+=',
    '-=',
    '*=',
    '**=',
    '/=',
    '%=',
  ],

  booleans: ['verdadeiro', 'falso', 'vazio', 'nulo'],

  typeKeywords: ['var'],

  strings: [],
  comments: [],
  numbers: [],
  rest: [],
}
