export const QUOTES = [
  'O universo é um vasto oceano de estrelas, esperando ser explorado.',
  'Entre as estrelas, navegamos pelo cosmos infinito.',
  'Nas fronteiras do espaço, a beleza cósmica nos envolve.',
  'Em um céu estrelado, cada ponto de luz conta bilhões de anos.',
  'As galáxias dançam em um espetáculo cósmico.',
  'A escuridão do espaço revela segredos cósmicos.',
  'Exploradores do espaço, viajamos como nômades das estrelas.',
  'A órbita da Lua influencia as marés de nossos corações.',
  'Nas vastas extensões do universo, somos apenas uma centelha de luz.',
  'Cada estrela é uma promessa de aventuras inexploradas.',
  'Ao contemplar a escuridão do espaço, percebemos a magnitude de nossa jornada.',
  'No vácuo do espaço, o silêncio ecoa histórias antigas de estrelas que se apagaram.',
  'O espaço, uma tapeçaria de constelações, conta histórias além da nossa compreensão.',
  'Em uma noite estrelada, a Via Láctea se revela como um rio de luz.',
  'Os planetas dançam em torno do sol, uma coreografia celestial ao longo de bilhões de anos.',
]
