import type { Context, Input, Next } from 'hono'
import type { BlankEnv } from 'hono/types'
import { getCookie, setCookie, deleteCookie } from 'hono/cookie'
import type { StatusCode } from 'hono/utils/http-status'
import type { SupabaseClient } from '@supabase/supabase-js'

import type { Http, HttpMethod } from '@stardust/core/global/interfaces'
import { RestResponse } from '@stardust/core/global/responses'
import type { UserDto } from '@stardust/core/profile/entities/dtos'
import { AppError } from '@stardust/core/global/errors'
import { HTTP_STATUS_CODE } from '@stardust/core/global/constants'

import type { InngestAmqp } from '@/queue/inngest/InngestAmqp'

type HonoContext = Context<BlankEnv, any, Input>

type Schema = {
  json?: unknown
  param?: unknown
  query?: unknown
}

type HonoHttpSchema<HttpSchema extends Schema> = {
  body: HttpSchema['json']
  routeParams: HttpSchema['param']
  queryParams: HttpSchema['query']
}

export class HonoHttp<HttpSchema extends Schema>
  implements Http<HonoHttpSchema<HttpSchema>, Response>
{
  private readonly context: HonoContext
  private readonly next?: Next
  readonly schema?: HonoHttpSchema<HttpSchema>

  constructor(context: HonoContext, next?: Next) {
    this.context = context
    this.next = next
  }

  getCurrentRoute(): string {
    return this.context.req.url
  }

  redirect(route: string): RestResponse<Response> {
    const body = this.context.redirect(route)
    return new RestResponse({
      body,
      statusCode: body.status,
      headers: {
        'X-Hono-Response': 'true',
      },
    })
  }

  async getBody(): Promise<HonoHttpSchema<HttpSchema>['body']> {
    // @ts-ignore
    return this.context.req.valid('json')
  }

  getRouteParams(): HonoHttpSchema<HttpSchema>['routeParams'] {
    // @ts-ignore
    return this.context.req.valid('param')
  }

  getQueryParams(): HonoHttpSchema<HttpSchema>['queryParams'] {
    // @ts-ignore
    return this.context.req.valid('query')
  }

  async getUser(): Promise<UserDto> {
    return (await this.context.req.json()) as UserDto
  }

  getMethod(): HttpMethod {
    return this.context.req.method as HttpMethod
  }

  setCookie(key: string, value: string, duration: number): void {
    setCookie(this.context, key, value, {
      maxAge: duration,
      path: '/',
    })
  }

  async getCookie(key: string): Promise<string | null> {
    return getCookie(this.context, key) ?? null
  }

  async deleteCookie(key: string): Promise<void> {
    deleteCookie(this.context, key)
  }

  async hasCookie(key: string): Promise<boolean> {
    return this.getCookie(key) !== null
  }

  async pass(): Promise<RestResponse<Response>> {
    if (!this.next) throw new AppError('HonoHttp next is not defined')

    await this.next()
    return new RestResponse()
  }

  statusOk(): this {
    this.context.status(HTTP_STATUS_CODE.ok)
    return this
  }

  statusCreated(): this {
    this.context.status(HTTP_STATUS_CODE.created)
    return this
  }

  statusNoContent(): this {
    this.context.status(HTTP_STATUS_CODE.noContent)
    return this
  }

  send(data: unknown): RestResponse<Response> {
    const body = this.context.json(data as object)
    return new RestResponse({
      body,
      statusCode: body.status,
      headers: {
        'X-Hono-Response': 'true',
      },
    })
  }

  /**
   * Processes a RestResponse and returns an appropriate HTTP response.
   * 
   * If the `X-Hono-Response` header is set to 'true', the response is treated
   * as an internal response generated by the `send` method and returned directly.
   * Otherwise, the response is processed further to set the status code and
   * return a JSON object containing the response body or an error message.
   */
  sendResponse(response: RestResponse): Response {
    if (response.getHeader('X-Hono-Response') === 'true') {
      return response.body as Response
    }

    this.context.status(response.statusCode as StatusCode)

    if (response.isFailure) {
      return this.context.json({
        error: response.errorMessage,
      })
    }
    return this.context.json(response.body ?? {})
  }

  getSupabase(): SupabaseClient {
    return this.context.get('supabase')
  }

  getInngest(): InngestAmqp<void> {
    return this.context.get('inngest')
  }
}
