@URL = {{BASE_URL}}/auth
@EMAIL = ctrlaltdel.cursor@gmail.com

### Sign in
POST {{URL}}/sign-in
Content-Type: application/json

{
  "email": "{{EMAIL}}",
  "password": "123456"
}

### Sign up
POST {{URL}}/sign-up
Content-Type: application/json

{
  "email": "{{EMAIL}}",
  "password": "123456",
  "name": "Ctrl Alt Del"
}

### Sign out
DELETE {{URL}}/sign-out

### Resend sign up email
POST {{URL}}/resend-email/sign-up
Content-Type: application/json

{
  "email": "{{EMAIL}}"
}

### Request password reset
POST {{URL}}/request-password-reset
Content-Type: application/json

{
  "email": "{{EMAIL}}"
}

### Confirm email
POST {{URL}}/confirm-email
Content-Type: application/json

{
  "token": "5e48b989c9313315a1c3b397d4b06efc9ea77f08b92366bbd28ba71e"
}

### Confirm password reset
POST {{URL}}/confirm-password-reset
Content-Type: application/json

{
  "token": "6eaa5b310fefda81e5ea6c88f104c47384b55245797b19a93dd7cbeb"
}

### Reset password
PATCH {{URL}}/reset-password
Content-Type: application/json

{
  "newPassword": "654321",
  "accessToken": "accessToken",
  "refreshToken": "refreshToken"
}

### Refresh session
POST {{URL}}/refresh-session
Content-Type: application/json

{
  "refreshToken": "xugtmelpndgf"
}

### Fetch account
GET {{URL}}/account
Authorization: Bearer {{JWT}}
