@URL = {{BASE_URL}}/storage/files
@FILE_NAME = abacaxi.jpg
@FOLDER = story

### Get files
GET {{URL}}/{{FOLDER}}
?page=1
&itemsPerPage=25
&search=
Authorization: Bearer {{JWT}}

### Remove file
DELETE {{URL}}/{{FOLDER}}/{{FILE_NAME}}
Authorization: Bearer {{JWT}}

### Search guides
GET {{URL}}/{{FOLDER}}
?query=Delegua
&namespace=guides
&topK=1
Authorization: Bearer {{JWT}}
