@URL = {{BASE_URL}}/storage
@FILE_NAME = abacaxi.jpg
@FOLDER = story

### Get files
GET {{URL}}/{{FOLDER}}
?page=1
&itemsPerPage=25
&search=
Authorization: Bearer {{JWT}}

### Remove file
DELETE {{URL}}/{{FOLDER}}/{{FILE_NAME}}
Authorization: Bearer {{JWT}}
