@URL = {{BASE_URL}}/challenging/challenges
@CHALLENGE_ID = be477773-1294-4278-b339-58f71ee264bd
@SLUG = area-do-escudo-protetor
@STAR_ID = bda4c82c-9466-4619-bdd6-89f719c54c27

### Fetch challenge by slug
GET {{URL}}/slug/{{SLUG}}

### Fetch challenge by star
GET {{URL}}/star/{{STAR_ID}}
Authorization: Bearer {{JWT}}

### Fetch challenges list
GET {{URL}}
?page=1
&itemsPerPage=10
&title=
&difficulty=any
&completionStatus=completed
&upvotesCountOrder=any
&postingOrder=any

### Fetch completed challenges count by difficulty level
GET {{URL}}/completed-by-difficulty-level
Authorization: Bearer {{JWT}}

### Fetch challenge vote
GET {{URL}}/{{CHALLENGE_ID}}/vote
Authorization: Bearer {{JWT}}

### Fetch all categories
GET {{URL}}/categories

### Fetch challenge vote
GET {{URL}}/{{CHALLENGE_ID}}/vote
Authorization: Bearer {{JWT}}

### Post challenge
POST {{URL}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "title": "O problema dos 3 corpos",
  "code": "funcao encontreCorpos(parametro1) {\n\n}",
  "slug": "o-problema-dos-3-corpos",
  "difficultyLevel": "easy",
  "author": {
    "id": "2ac3e189-e5ed-4003-a87a-d2358411584e"
  },
  "categories": [
    {
      "id": "818af4aa-ee10-4dd8-9adb-ff9f2ad1eb97",
      "name": "condicionais"
    },
    {
      "id": "28a2f573-717d-47e0-91b3-aabf7ff817dc",
      "name": "dicionarios"
    }
  ],
  "languages": [],
  "completionsCount": 0,
  "description": "minha descrição",
  "downvotesCount": 0,
  "isPublic": false,
  "postedAt": "Tue Nov 11 2025 11:52:29 GMT-0300 (Horário Padrão de Brasília)",
  "results": [],
  "starId": null,
  "testCases": [
    {
      "expectedOutput": "minha resposta",
      "inputs": [
        "valorDoParametro"
      ],
      "isLocked": false,
      "position": 1
    },
    {
      "expectedOutput": "minha resposta 2",
      "inputs": [
        "parametro2"
      ],
      "isLocked": false,
      "position": 2
    },
    {
      "expectedOutput": "minha resposta 3",
      "inputs": [
        "parametro3"
      ],
      "isLocked": false,
      "position": 3
    }
  ],
  "upvotesCount": 0,
  "userOutputs": []
}

### Update challenge
PUT {{URL}}/{{CHALLENGE_ID}}
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
  "title": "O problema dos 8 corpos",
  "code": "funcao encontreCorpos(parametro2) {\n\n}",
  "difficultyLevel": "medium",
  "author": {
    "id": "2ac3e189-e5ed-4003-a87a-d2358411584e"
  },
  "categories": [
    {
      "id": "818af4aa-ee10-4dd8-9adb-ff9f2ad1eb97",
      "name": "condicionais"
    },
    {
      "id": "28a2f573-717d-47e0-91b3-aabf7ff817dc",
      "name": "dicionarios"
    }
  ],
  "languages": [],
  "completionsCount": 0,
  "description": "minha descrição",
  "downvotesCount": 0,
  "isPublic": false,
  "postedAt": "Tue Nov 11 2025 11:52:29 GMT-0300 (Horário Padrão de Brasília)",
  "results": [],
  "starId": null,
  "testCases": [
    {
      "expectedOutput": "minha resposta",
      "inputs": [
        "valorDoParametro"
      ],
      "isLocked": false,
      "position": 1
    },
    {
      "expectedOutput": "minha resposta 2",
      "inputs": [
        "parametro2"
      ],
      "isLocked": false,
      "position": 2
    },
    {
      "expectedOutput": "minha resposta 3",
      "inputs": [
        "parametro3"
      ],
      "isLocked": false,
      "position": 3
    }
  ],
  "upvotesCount": 0,
  "userOutputs": []
}

### Vote challenge
POST {{URL}}/{{CHALLENGE_ID}}/vote
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
  "challengeVote": "downvote"
}

### Delete challenge
DELETE {{URL}}/{{CHALLENGE_ID}}
Authorization: Bearer {{JWT}}

