@URL = {{BASE_URL}}/challenging/challenges
@SLUG = "challenge-slug"

### Fetch challenge by slug
GET {{URL}}/slug/{{SLUG}}
Authorization: Bearer {{JWT}}

### Fetch challenges list
GET http://localhost:3333/challenging/challenges?page=1&itemsPerPage=10&title=&difficulty=any&upvotesCountOrder=descending&postingOrder=any&completionStatus=any
Authorization: Bearer {{JWT}}

### Fetch completed challenges count by difficulty level
GET {{URL}}/completed-by-difficulty-level
Authorization: Bearer {{JWT}}
