@URL = {{BASE_URL}}/profile/achievements
@ACHIEVEMENT_ID = 56ab2a6d-39f7-4fba-a001-f33ccbe39dfe
@USER_ID = 76dc903b-eeae-45a3-9ed1-43240249e457

### Fetch achievements
GET {{URL}} 
Authorization: Bearer {{JWT}}

### Fetch all unlocked achievements
GET {{URL}}/{{USER_ID}} 
Authorization: Bearer {{JWT}}

### Observe new unlocked achievements
POST {{URL}}/{{USER_ID}}/observe
Authorization: Bearer {{JWT}}

### Rescue achievement
PUT {{URL}}/{{USER_ID}}/{{ACHIEVEMENT_ID}}/rescue
Authorization: Bearer {{JWT}}