@URL = {{BASE_URL}}/profile/users
@USER_ID = 56ab2a6d-39f7-4fba-a001-f33ccbe39dfe 

### Fetch user
GET {{URL}}/{{USER_ID}} 

### Update user
PUT {{URL}}/{{USER_ID}}

{
  "name": "Jane Doe",
  "email": "jane.doe@example.com",
  "slug": "jane-doe",
  "avatarId": "avatar id",
  "rocketId": "rocket id",
  "tierId": "tier id",
  "coins": 150,
  "xp": 1200,
  "weeklyXp": 300,
  "streak": 5,
  "level": 7,
  "weekStatus": ["todo", "done", "todo", "todo", "todo", "todo", "todo"]
}

### Verify user name in use
POST {{URL}}/verify-name-in-use

{
  "name": "Jane Doe"
}

### Verify user email in use
POST {{URL}}/verify-email-in-use

{
  "email": "jane.doe@example.com"
}