import { createStep, createWorkflow } from '@mastra/core/workflows'
import z from 'zod'

import { challengeSchema } from '@stardust/validation/challenging/schemas'
import type { CreateChallengeWorkflow } from '@stardust/core/challenging/interfaces'

import { ChallengingToolkit } from '../toolkits/ChallengingToolkit'
import { ChallengingSquad } from '../squads/ChallengingSquad'

export class MastraCreateChallengeWorkflow implements CreateChallengeWorkflow {
  async run() {
    const getNextChallengeSourceStep = this.getNextChallengeSource()
    const createChallengeStep = this.createChallenge()
    const parseDraftStep = this.parseChallengeDraft()
    const postChallengeStep = this.postChallenge()

    const workflow = createWorkflow({
      id: 'create-challenge-workflow',
      inputSchema: z.void(),
      outputSchema: z.void(),
    })
      .then(getNextChallengeSourceStep)
      .map(async ({ inputData }) => ({
        prompt: `URL da fonte: ${inputData.url}. Instruções adicionais: ${inputData.additionalInstructions ?? 'nenhuma'}.`,
      }))
      .then(createChallengeStep)
      .then(parseDraftStep)
      .map(async ({ inputData, getStepResult }) => {
        const challengeSource = getStepResult(getNextChallengeSourceStep)
        return {
          ...inputData,
          challengeSourceId: challengeSource.id,
        }
      })
      .then(postChallengeStep)
      .commit()

    const run = await workflow.createRun()
    try {
      await run.start({ inputData: undefined })
    } catch (error) {
      run.cancel()
      throw error
    }
  }

  private getNextChallengeSource() {
    return createStep(ChallengingToolkit.getNextChallengeSourceTool)
  }

  private createChallenge() {
    return createStep(ChallengingSquad.challengingCreatorAgent)
  }

  private parseChallengeDraft() {
    const parsedChallengeSchema = challengeSchema.omit({ author: true, isPublic: true })

    return createStep({
      id: 'parse-challenge-draft-step',
      description: 'Parse challenge draft generated by agent',
      inputSchema: z.object({ text: z.string() }),
      outputSchema: parsedChallengeSchema,
      execute: async ({ inputData }) => {
        const parsed = JSON.parse(inputData.text)
        return parsedChallengeSchema.parse(parsed)
      },
    })
  }

  private postChallenge() {
    return createStep(ChallengingToolkit.postChallengingTool)
  }
}
