export type AnimationName =
  | 'apollo-crying'
  | 'apollo-asking'
  | 'apollo-denying'
  | 'apollo-earning'
  | 'apollo-riding-rocket'
  | 'rocket-lauching'
  | 'rocket-floating'
  | 'rocket-exploring'
  | 'unlocked-star'
  | 'space'
  | 'streak'
  | 'spinner'
  | 'shinning'
  | '404'
