import {
  Anchor,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  Envelope,
  EyeClosed,
  Prohibit,
  CalendarBlank,
  Check,
  CheckCircle,
  Circle,
  SignIn,
  Eye,
  X,
  DotsThreeOutlineVertical,
  Terminal,
  PlusCircle,
  User,
  List,
  Layout,
  Quotes,
  FileCode,
  GearSix,
  Shield,
  Lock,
  Clock,
  ChartLine,
  PaperPlaneRight,
  ChatText,
  ShareNetwork,
  ChatCircleText,
  ChatCircle,
  TextH,
  ListNumbers,
  ListBullets,
  Target,
  ThumbsUp,
  ThumbsDown,
  Power,
  Rocket,
  Code,
  Minus,
  Flag,
  ArrowsDownUp,
  TerminalWindow,
  Article,
} from '@phosphor-icons/react/dist/ssr'

import type { IconName } from '../types/IconName'
import type { Icon } from '@phosphor-icons/react'

export const ICONS: Record<IconName, Icon> = {
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-down': ArrowsDownUp,
  'eye-closed': EyeClosed,
  'stop-sign': Prohibit,
  'sign-out': Power,
  'three-dots': DotsThreeOutlineVertical,
  'simple-arrow-up': CaretUp,
  'simple-arrow-down': CaretDown,
  'simple-arrow-left': CaretLeft,
  'simple-arrow-right': CaretRight,
  'runnable-code': TerminalWindow,
  'text-block': ChatCircleText,
  'strong-text-block': ChatText,
  'ordered-list': ListNumbers,
  'unordered-list': ListBullets,
  comment: ChatCircle,
  title: TextH,
  strong: Article,
  send: PaperPlaneRight,
  share: ShareNetwork,
  link: Anchor,
  minus: Minus,
  divider: Minus,
  quote: Quotes,
  menu: List,
  achievement: Flag,
  check: Check,
  checked: CheckCircle,
  code: Code,
  unchecked: Circle,
  upvote: ThumbsUp,
  downvote: ThumbsDown,
  rate: ChartLine,
  target: Target,
  clock: Clock,
  layout: Layout,
  calendar: CalendarBlank,
  shield: Shield,
  gear: GearSix,
  terminal: Terminal,
  plus: PlusCircle,
  person: User,
  file: FileCode,
  enter: SignIn,
  eye: Eye,
  mail: Envelope,
  rocket: Rocket,
  home: Envelope,
  close: X,
  lock: Lock,
}
