@URL = {{BASE_URL}}/space/planets
@PLANET_ID = d5dc752f-31d6-4231-ae72-d05050fc69ee
@STAR_ID = fac02b8f-0286-4772-838e-5e2f1a071bc4

### Fetch planets
GET {{URL}}
Authorization: Bearer {{JWT}}

### Create planet
POST {{URL}}
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
  "name": "Planeta novo",
  "icon": "icon.png",
  "image": "image.png"
}

### Update planet
PUT {{URL}}/{{PLANET_ID}}
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
  "name": "Planeta editado de novo",
  "icon": "eita.png",
  "image": "imagem2.png"
}

### Reorder planets
PUT {{URL}}/list/order
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
  "planetIds": ["8c3b6cab-d3c6-4d64-8701-c580d4a6d31a"]
}

### Create planet star
POST {{URL}}/{{PLANET_ID}}/stars
Authorization: Bearer {{JWT}}

### Reorder planet stars
PUT {{URL}}/{{PLANET_ID}}/stars
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
  "starIds": []
}

### Delete planet
DELETE {{URL}}/{{PLANET_ID}}
Authorization: Bearer {{JWT}}

### Delete planet star
DELETE {{URL}}/{{PLANET_ID}}/stars/{{STAR_ID}}
Authorization: Bearer {{JWT}}
