@URL = {{BASE_URL}}/space/stars
@STAR_SLUG = logica-de-programacao
@STAR_ID = b5698598-cd2a-44de-b560-31798581f9e5

### Fetch star by slug
GET {{URL}}/slug/{{STAR_SLUG}}
Authorization: Bearer {{JWT}}

### Fetch star by id
GET {{URL}}/id/{{STAR_ID}}
Authorization: Bearer {{JWT}}

### Edit star name
PATCH {{URL}}/{{STAR_ID}}/name
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
  "name": "Lógica de Programação"
}

### Edit star availability
PATCH {{URL}}/{{STAR_ID}}/availability
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
  "isAvailable": false
}

### Edit star type
PATCH {{URL}}/{{STAR_ID}}/type
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
  "isChallenge": false
}