import type { AnimationName } from '../types'

export const LOTTIE_PATHS: Record<AnimationName, string> = {
  '404': '/lotties/404.json',
  'apollo-crying': '/lotties/apollo-crying.json',
  'apollo-asking': '/lotties/apollo-asking.json',
  'apollo-denying': '/lotties/apollo-denying.json',
  'apollo-earning': '/lotties/apollo-earning.json',
  'apollo-missing': '/lotties/apollo-missing.json',
  'apollo-riding-rocket': '/lotties/apollo-riding-rocket.json',
  'rocket-lauching': '/lotties/rocket-launching.json',
  'rocket-floating': '/lotties/rocket-floating.json',
  'rocket-crossing-sky': '/lotties/rocket-crossing-sky.json',
  'rocket-exploring': '/lotties/rocket-exploring.json',
  'apollo-congratulating': '/lotties/apollo-congratulating.json',
  'apollo-greeting': '/lotties/apollo-greeting.json',
  'unlocked-star': '/lotties/unlocked-star.json',
  'planets-exploration': '/lotties/planets-exploration.json',
  'fast-rocket': '/lotties/fast-rocket.json',
  'internal-error': '/lotties/internal-error.json',
  galaxy: '/lotties/galaxy.json',
  coins: '/lotties/coins.json',
  hourglass: '/lotties/hourglass.json',
  spiral: '/lotties/spiral.json',
  podium: '/lotties/podium.json',
  trophy: '/lotties/trophy.json',
  shinning: '/lotties/reward-shinning.json',
  streak: '/lotties/streak.json',
  space: '/lotties/space.json',
  spinner: '/lotties/spinner.json',
  robot: '/lotties/robot.json',
}
