export const CACHE = {
  keys: {
    authUser: '/auth-user',
    userAchievements: '/user-achievements',
    challengesSummary: '/challenges-summary',
    challengesList: '/challenges-list',
    solutionsList: '/solutions-list',
    snippetsList: '/snippets-list',
    userChallengesList: '/user-challenges-list',
    userSolutionsList: '/solutions-list',
    userCompletedChallenges: '/user-completed-challenges',
    commentReplies: '/comment-replies',
    filteredAvatars: '/filtered-avatars',
    filteredRockets: '/filtered-rockets',
    comments: '/comments',
    userUpvotedCommentsIds: '/user-upvoted-comments-ids',
    acquiredAvatarsIds: '/acquired-avatars-ids',
    shopAvatars: '/shop/avatar',
    shopRockets: '/shop/rocket',
    shopInsignias: '/shop/insignia',
    playgroundCards: '/playground-cards',
    rankingsList: '/rankings-list',
    docs: '/docs',
    googleAccountConnection: '/google-account-connection',
    githubAccountConnection: '/github-account-connection',
  },
}
