export type TextEditorWidget =
  | 'title'
  | 'strong'
  | 'orderedList'
  | 'unorderedList'
  | 'textBlock'
  | 'imageBlock'
  | 'alertTextBlock'
  | 'quoteTextBlock'
  | 'userTextBlock'
  | 'codeLine'
  | 'runnableCodeBlock'
  | 'codeBlock'
  | 'link'
