export { SelectedAvatarByDefaultNotFoundError } from './SelectedAvatarByDefaultNotFoundError'
export { SelectedRocketByDefaultNotFoundError } from './SelectedRocketByDefaultNotFoundError'
export { AvatarNotFoundError } from './AvatarNotFoundError'
export { RocketNotFoundError } from './RocketNotFoundError'
export { InsigniaNotFoundError } from './InsigniaNotFoundError'
export { InsigniaAlreadyExistsError } from './InsigniaAlreadyExistsError'
