@URL = {{BASE_URL}}/playground/snippets
@SNIPPET_ID = c3e6b0d0-dd8a-4370-a730-9a40f5e2d5f4

### Create snippet
POST {{URL}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "title": "Snippet de teste",
  "code": "escreva('Olá, mundo!');",
  "isPublic": true
}

### Fetch snippet
GET {{URL}}/{{SNIPPET_ID}}
Authorization: Bearer {{JWT}}

### Fetch snippets list
GET {{URL}}
?page=1
&itemsPerPage=10
Authorization: Bearer {{JWT}}

### Edit snippet
PUT {{URL}}/{{SNIPPET_ID}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "title": "Snippet de teste editado",
  "code": "escreva('Código editado!')",
  "isPublic": false
}

### Delete snippet
DELETE {{URL}}/{{SNIPPET_ID}}
Authorization: Bearer {{JWT}}
