import {
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  Envelope,
  EyeClosed,
  Prohibit,
  CalendarBlank,
  Check,
  CheckCircle,
  Circle,
  SignIn,
  Eye,
  X,
  Terminal,
  PlusCircle,
  List,
  FileCode,
  GearSix,
  Shield,
  Lock,
  Clock,
  ChartLine,
  Target,
  Power,
  Rocket,
  Flag,
  ArrowsDownUp,
} from '@phosphor-icons/react/dist/ssr'

import type { IconName } from '../types/IconName'
import type { Icon } from '@phosphor-icons/react'

export const ICONS: Record<IconName, Icon> = {
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-down': ArrowsDownUp,
  'eye-closed': EyeClosed,
  'stop-sign': Prohibit,
  'sign-out': Power,
  'three-dots': List,
  'simple-arrow-up': CaretUp,
  'simple-arrow-down': CaretDown,
  'simple-arrow-left': CaretLeft,
  'simple-arrow-right': CaretRight,
  achievement: Flag,
  check: Check,
  checked: CheckCircle,
  unchecked: Circle,
  rate: ChartLine,
  target: Target,
  clock: Clock,
  calendar: CalendarBlank,
  shield: Shield,
  gear: GearSix,
  terminal: Terminal,
  plus: PlusCircle,
  file: FileCode,
  enter: SignIn,
  eye: Eye,
  mail: Envelope,
  rocket: Rocket,
  home: Envelope,
  close: X,
  lock: Lock,
}
