@URL = {{BASE_URL}}/lesson/questions
@STAR_ID = 1f1b43e7-916a-438c-9d2d-c8065c5996a9

### Fetch questions
GET {{URL}}/star/{{STAR_ID}}
Authorization: Bearer {{JWT}}

### Update questions
PUT {{URL}}/star/{{STAR_ID}}
Authorization: Bearer {{JWT}}

{}