@URL = {{BASE_URL}}/lesson/questions
@STAR_ID = efdde01e-242e-4a15-bf09-10cbb4bd74ca 

### Fetch questions
GET {{URL}}/star/{{STAR_ID}}
Authorization: Bearer {{JWT}}

### Update questions
PUT {{URL}}/star/{{STAR_ID}}
Authorization: Bearer {{JWT}}

{}