export const CACHE = {
  keys: {
    authUser: '/auth-user',
    userAchievements: '/user-achievements',
    challengesSummary: '/challenges-summary',
    challengesList: '/challenges-list',
    userCompletedChallenges: '/user-completed-challenges',
    commentReplies: '/comment-replies',
    filteredAvatars: '/filtered-avatars',
    filteredRockets: '/filtered-rockets',
    comments: '/comments',
    userUpvotedCommentsIds: '/user-upvoted-comments-ids',
    acquiredAvatarsIds: '/acquired-avatars-ids',
    avatar: '/avatar',
    rocket: '/rocket',
    playgroundCards: '/playground-cards',
    ranking: 'ranking',
    rankingsList: 'rankings-list',
    solutions: '/solutions',
  },
}
