name: Core package CI 

on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        working-directory: packages/core

      - name: Run tests
        run: npm run test
        working-directory: packages/core
     

      