name: Core package CI

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "package.json"
      - "package-lock.json"
      - "packages/core/**"
      - ".dependency-cruiser.cjs"
      - "knip.json"

env:
  NODE_VERSION: "22"

jobs:
  check-code:
    name: Check code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check code
        run: npm run check:code -w @stardust/core

  check-types:
    name: Check types
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm run check:types -w @stardust/core

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build LSP package
        run: npm run build -w @stardust/lsp

      - name: Run tests
        run: npm run test:unit -w @stardust/core

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - check-code
      - check-types
      - tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build:core
