name: Server app CD to Heroku

on:
  push:
    branches:
      - main
    paths:
      - "apps/server/**"
      - "packages/core/**"
      - "packages/validation/**"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      HEROKU_APP_NAME: stardust-server-app
      IMAGE_NAME: registry.heroku.com/stardust-server-app/server

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: Infisical/secrets-action@v1.0.9
        with:
          method: "oidc"
          identity-id: ${{ secrets.INFISICAL_IDENTITY_ID }}
          domain: "https://app.infisical.com"
          env-slug: "prod"
          project-slug: "stardust-server-app"
          export-type: "file"
          file-output-path: "/apps/server/.env"

      - name: Ensure Heroku find the correct Dockerfile for server app
        run: rm Dockerfile.web && mv Dockerfile.server Dockerfile.web

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Set Heroku stack to container
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku stack:set container --app ${{ env.HEROKU_APP_NAME }}

      - name: Build and push Docker image to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push web -a ${{ env.HEROKU_APP_NAME }} --recursive

      - name: Release to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a ${{ env.HEROKU_APP_NAME }} web
