name: Server app CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "apps/server/**"
      - "packages/core/**"
      - "packages/validation/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install
        working-directory: apps/server

      - name: Check types
        run: npm run check-types
        working-directory: apps/server

      - name: Install turbo
        run: npm install -g turbo

      - name: Build project
        run: npm run build:server

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Setup Supabase
        run: supabase start

      - name: Run migrations
        run: supabase migration up

      - uses: Infisical/secrets-action@v1.0.9
        with:
          method: "oidc"
          identity-id: ${{ secrets.INFISICAL_IDENTITY_ID }}
          domain: ${{ secrets.INFISICAL_DOMAIN }}
          env-slug: "test"
          project-slug: "stardust-server-app"
          export-type: "file"
          file-output-path: "/apps/server/.env.testing"

      - name: Run tests
        run: npm run test
        working-directory: apps/server
