name: web-app-cd

on:
  push:
    branches:
      - clean-arch

env:
  PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_RUN_PROJECT_ID }}
  REGION: us-east1
  REPO_NAME: stardust-webgg

jobs:
  setup-build-and-deploy:
    name: Setup, Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_CLOUD_RUN_SERVICE_ACCOUNT }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Create .env file
        run: echo "${{ secrets.WEB_ENV }}" >> apps/web/.env

      - name: Build and tag the Docker image
        run: |
          docker build -t grc.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA -f apps/web/Dockerfile .

      - name: Deploy
        run: |
          gcloud run deploy $REPO_NAME \
          --region $REGION \
          --image gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
          --platform "managed" \
          --quiet
