name: Web app CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "apps/web/**"
      - "packages/core/**"
      - "packages/validation/**"
      - "packages/lsp/**"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install
        working-directory: apps/web

      - name: Check types
        run: npm run check-types
        working-directory: apps/web

      - uses: Infisical/secrets-action@v1.0.9
        with:
          method: "oidc"
          identity-id: ${{ secrets.INFISICAL_IDENTITY_ID }}
          domain: ${{ secrets.INFISICAL_DOMAIN}}
          env-slug: "staging"
          project-slug: "stardust-web-app"
          export-type: "file"
          file-output-path: "/apps/web/.env.test"

      - name: Run tests
        run: npm run test
        working-directory: apps/web

      - name: Install turbo
        run: npm install -g turbo

      - name: Build project
        run: npm run build:web
