name: Web app CI 

on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        working-directory: apps/web

      - name: Check types
        run: npm run check-types
        working-directory: apps/web

      - name: Run tests
        run: npm run test
        working-directory: apps/web

      - name: Install turbo
        run: npm install -g turbo

      - name: Build project
        run: npm run build:web

      