name: Web app CD to Azure

on:
  push:
    branches:
      - main
    paths:
      - "apps/web/**"

env:
  AZURE_WEBAPP_NAME: stardust-web-app
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: joaopetros
  IMAGE_NAME: joaopetros/stardust-web-app

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo "${{ secrets.WEB_ENV }}" >> apps/web/.env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and tag the Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} -f apps/web/Dockerfile .
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
          images: ${{ env.IMAGE_NAME }}:${{ github.sha }}
