import {
  User,
  Flag,
  Globe,
  X as Close,
  Terminal,
  Star,
  Rocket,
  LayoutDashboard,
  Settings,
  ShoppingCart,
  Plus,
  SquarePen,
  GripVertical,
  BookMarked,
  BookUp,
  TrendingUp,
  Contact,
  TrendingDown,
  Award,
  Loader2,
  RotateCcw,
  Copy,
  LogOut,
  ChevronDown,
  HardDriveUpload,
  ChevronUp,
  BookOpen,
  HelpCircle,
  Loader,
  Upload,
  Image,
  Trash,
  Minus,
  Check,
  Heading,
  Type,
  Quote,
  AlertTriangle,
  ListOrdered,
  List,
  Code,
  FileCode,
  Link,
  type LucideIcon,
} from 'lucide-react'

import type { IconName } from '../types/IconName'

export const ICONS: Record<IconName, LucideIcon> = {
  'arrow-down': ChevronDown,
  'arrow-up': ChevronUp,
  'sign-out': LogOut,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'lsp-guide': BookMarked,
  'mdx-guide': BookUp,
  minus: Minus,
  insignia: Award,
  avatar: Contact,
  image: Image,
  user: User,
  achievement: Flag,
  planet: Globe,
  challenge: Terminal,
  dashboard: LayoutDashboard,
  x: Close,
  edition: SquarePen,
  star: Star,
  check: Check,
  trash: Trash,
  draggable: GripVertical,
  submit: HardDriveUpload,
  rocket: Rocket,
  loading: Loader2,
  spinner: Loader,
  history: BookOpen,
  questions: HelpCircle,
  copy: Copy,
  upload: Upload,
  reload: RotateCcw,
  plus: Plus,
  configuration: Settings,
  shop: ShoppingCart,
  title: Heading,
  'text-block': Type,
  'strong-text-block': Quote,
  alert: AlertTriangle,
  'ordered-list': ListOrdered,
  'unordered-list': List,
  code: Code,
  'runnable-code': FileCode,
  link: Link,
}
