import {
  User,
  Flag,
  Globe,
  X as Close,
  Terminal,
  Star,
  Rocket,
  LayoutDashboard,
  SquarePen,
  GripVertical,
  Loader2,
  Copy,
  ChevronDown,
  HardDriveUpload,
  ChevronUp,
  BookOpen,
  HelpCircle,
  Loader,
  Upload,
  Image,
  Trash,
  type LucideIcon,
} from 'lucide-react'

import type { IconName } from '../types/IconName'

export const ICONS: Record<IconName, LucideIcon> = {
  'arrow-down': ChevronDown,
  'arrow-up': ChevronUp,
  image: Image,
  user: User,
  achievement: Flag,
  planet: Globe,
  challenge: Terminal,
  dashboard: LayoutDashboard,
  x: Close,
  edition: SquarePen,
  star: Star,
  trash: Trash,
  draggable: GripVertical,
  submit: HardDriveUpload,
  rocket: Rocket,
  loading: Loader2,
  spinner: Loader,
  history: BookOpen,
  questions: HelpCircle,
  copy: Copy,
  upload: Upload,
}
